# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cdbartSigmaFix_inf <- function(n, p, np, ixv, iyv, ixpv, SigmaInv, m, numcutv, nd, burn, mybeta, alpha, tau, dart, theta, omega, a, b, rho, aug, nkeeptrain, nkeeptest, nkeeptestme, nkeeptreedraws, printevery) {
    .Call(`_cbart_cdbartSigmaFix_inf`, n, p, np, ixv, iyv, ixpv, SigmaInv, m, numcutv, nd, burn, mybeta, alpha, tau, dart, theta, omega, a, b, rho, aug, nkeeptrain, nkeeptest, nkeeptestme, nkeeptreedraws, printevery)
}

